### PR TITLE
feat: output stdout

### LINKED ISSUE #183: Print stdout in Hg log
> English is not my first language, so please forgive my grammatical errors

I added a pre-commit hook to the hg repository that uses eslint to check for syntax errors, and when I commit the code via vscode-hg, if an error occurs with eslint, it commits terminal, but I can't see any hint about the eslint rule in the hg ouput.

I see the following output.
```bash
error Command failed with exit code 1.
abort: pre-commit hook exited with status 1

error Command failed with exit code 1.
abort: pre-commit hook exited with status 1
```

Output of the terminal:
```bash
$ eslint '**/*.js' --cache --fix

/Users/4ark/project/helper/404.js
  9:7  error  'a' is assigned a value but never used  no-unused-vars

✖ 1 problem (1 error, 0 warnings)

error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

I think this is because vscode-hg only prints stderr, not stdout. 

This is the internal implementation that I know through the source code:
- https://github.com/mrcrowl/vscode-hg/blob/8661ee183e6d2aea9f6c8a53f5171c86644d50ea/src/hg.ts#L620

Because I see that vscode sees the eslint rule error when doing a git commit. I would expect vscode-hg to have the same behaviour (perhaps an optional feature)

thx!

version:
- vscode: 1.65.2
- vscode-hg: v1.8.0

### PR DESCRIPTION
**Pull request by gd4Ark**
close #183 

image

### CODE REVIEW

**Comment by mrcrowl** [comment]
Thanks for the pickup, @gd4Ark. 

@incidentist / @hdpoliveira, can you please confirm that you are happy to include stdout in logging as proposed here?

**Comment by gd4Ark** [comment]
I don't understand why CI format-check goes wrong, it works locally :(

**Comment by mrcrowl** [comment]
> I don't understand why CI format-check goes wrong, it works locally :(

Sorry, that's my bad @gd4Ark. Please rebase or merge with master then try push again.

**Comment by hdpoliveira** [comment]
I'm not opposed to this change.
I'd wait for @incidentist opinion before merging though, he has been way more active than me.

**Comment by incidentist** [comment]
Looks good to me. Thanks @gd4Ark!

**Comment by gd4Ark** [comment]
Sorry, I was wondering when this change will be released :)

**Pull request merged**
